name = "rolldorado-casino-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-casino.com.pt"
HMAC_KEY = "7a5dce0aa3dc5312f5366ec69ac7b9b8aecfd4a4934fe2b88bf025049ab8a757"
COOKIE_NAME = "67y"
PLAY_PATH = "play-now"
BUTTON_ID = "pfe0fd59f5c5a22e98d00b6515dba8cf0"
GATE_SALT = "36a50b0486eeec26"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "0f62"
CTA_SELECTOR = ".play-button"
