name = "rolldorado-casino-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-casino.com.pt"
HMAC_KEY = "7a5dce0aa3dc5312f5366ec69ac7b9b8aecfd4a4934fe2b88bf025049ab8a757"
COOKIE_NAME = "rit"
PLAY_PATH = "play"
BUTTON_ID = "pfe0fd59f5c5a22e98d00b6515dba8cf0"
GATE_SALT = "99f72649e64e271f"
